// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFxh2BTNitDBn9hS5c2nfTWhtq8Mflzxo',
    appId: '1:310076701710:web:bfcfdc874dfe66be69105f',
    messagingSenderId: '310076701710',
    projectId: 'appdemo-b5d9f',
    authDomain: 'appdemo-b5d9f.firebaseapp.com',
    storageBucket: 'appdemo-b5d9f.appspot.com',
    measurementId: 'G-NWMR30Q68F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl8QHW-XmOW-teHs0YczSAPwftyYpuke4',
    appId: '1:310076701710:android:7d4948e0314c31f369105f',
    messagingSenderId: '310076701710',
    projectId: 'appdemo-b5d9f',
    storageBucket: 'appdemo-b5d9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB84lKdXOgtEDKKldttIC-DC5Xo6fNpg-M',
    appId: '1:310076701710:ios:8a2f28d72a24b95e69105f',
    messagingSenderId: '310076701710',
    projectId: 'appdemo-b5d9f',
    storageBucket: 'appdemo-b5d9f.appspot.com',
    iosClientId: '310076701710-mqs1ls4jfk3kgvvmbbkshubpctpu6qfr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB84lKdXOgtEDKKldttIC-DC5Xo6fNpg-M',
    appId: '1:310076701710:ios:8a2f28d72a24b95e69105f',
    messagingSenderId: '310076701710',
    projectId: 'appdemo-b5d9f',
    storageBucket: 'appdemo-b5d9f.appspot.com',
    iosClientId: '310076701710-mqs1ls4jfk3kgvvmbbkshubpctpu6qfr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );
}
